// <auto-generated />
using System;
using GestorDeGastos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestorDeGastos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250818213508_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestorDeGastos.Models.Detalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreDetalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RubroId")
                        .HasColumnType("int");

                    b.Property<bool>("esActivo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("RubroId");

                    b.ToTable("Detalles");
                });

            modelBuilder.Entity("GestorDeGastos.Models.Gasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DetalleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaGasto")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Importe")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("RubroId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<bool>("esActivo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DetalleId");

                    b.HasIndex("RubroId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("GestorDeGastos.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("esActivo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("GestorDeGastos.Models.RolRubro", b =>
                {
                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("RubroId")
                        .HasColumnType("int");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("bit");

                    b.HasKey("RolId", "RubroId");

                    b.HasIndex("RubroId");

                    b.ToTable("RolRubros");
                });

            modelBuilder.Entity("GestorDeGastos.Models.Rubro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreRubro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("esActivo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Rubros");
                });

            modelBuilder.Entity("GestorDeGastos.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<bool>("esActivo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GestorDeGastos.Models.Detalle", b =>
                {
                    b.HasOne("GestorDeGastos.Models.Rubro", "Rubro")
                        .WithMany("Detalles")
                        .HasForeignKey("RubroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rubro");
                });

            modelBuilder.Entity("GestorDeGastos.Models.Gasto", b =>
                {
                    b.HasOne("GestorDeGastos.Models.Detalle", "Detalle")
                        .WithMany()
                        .HasForeignKey("DetalleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestorDeGastos.Models.Rubro", "Rubro")
                        .WithMany("Gastos")
                        .HasForeignKey("RubroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestorDeGastos.Models.Usuario", "Usuario")
                        .WithMany("Gastos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Detalle");

                    b.Navigation("Rubro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestorDeGastos.Models.RolRubro", b =>
                {
                    b.HasOne("GestorDeGastos.Models.Rol", "Rol")
                        .WithMany("RolRubros")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestorDeGastos.Models.Rubro", "Rubro")
                        .WithMany("RolRubros")
                        .HasForeignKey("RubroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Rubro");
                });

            modelBuilder.Entity("GestorDeGastos.Models.Usuario", b =>
                {
                    b.HasOne("GestorDeGastos.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("GestorDeGastos.Models.Rol", b =>
                {
                    b.Navigation("RolRubros");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("GestorDeGastos.Models.Rubro", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Gastos");

                    b.Navigation("RolRubros");
                });

            modelBuilder.Entity("GestorDeGastos.Models.Usuario", b =>
                {
                    b.Navigation("Gastos");
                });
#pragma warning restore 612, 618
        }
    }
}
